db:
  name: wp-database
  labels:
    app: db
    env: dev
    stack: wordpress
  image:
    repository: mongo
    tag: latest
    pullPolicy: Always
  replicas: 2
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    APP_ENV: dev
  containerPorts:
      mysql: 3306